### ISSUE TITLE
 Bug - User tests are failing because of beforeEach hook

### ISSUE THREAD

**Issue by AllKinds** [meateam/seal#21]
The beforeEach hook over [here](https://github.com/meateam/seal/blob/master/src/user/user.spec.ts) failed in some of the test runs.
@Shahar-Y - Make sure you understand why... (and detail the reason in a comment)
Then fix it

**Comment by Shahar-Y** [comment]
I suspect it might be because of the missing 'await' in the first line of the beforeEach.
I'd have to test it in the same environment it failed, though. Because on my computer it passes the tests.
Did it fail in travis? If so, how can I run it myself on the same environment?
Also, should I create a new branch for this bug or a general 'bugs' branch?

**Comment by Shahar-Y** [comment]
Fixed
